### ISSUE TITLE
Isn't (s/optional-key :body) s/Any redundant on Request

### ISSUE THREAD

**Issue by geraldodev** [Prismatic/fnhouse#28]
On

(s/defschema Request
  "A Ring-style request, one input to a fnhouse handler"
  {:uri-args KeywordMap
   :query-params KeywordMap
   (s/optional-key :body) s/Any
   s/Any s/Any})

Isn't the optional :body definition redundant because of subsequent s/Any s/Any ?

**Comment by w01fe** [comment]
Thanks.  It's functionally redundant, but IMO still provides documentation value.

**Comment by geraldodev** [comment]
Documentation of http specification ?



2015-04-14 15:45 GMT-03:00 Jason Wolfe <notifications@github.com>:

**Comment by w01fe** [comment]
of the assumptions we are making about Ring's format.

**Comment by geraldodev** [comment]
Thnx for sharing this work with us.
